- name: cart
  hosts: cart
  become: yes
  tasks:
  - name: enabling and disabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.package:
     name: nodejs
     state: present
  - name: creating roboshop user
    ansible.builtin.user: 
     name: roboshop
  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  - name: downloading cart code
    ansible.builtin.get_url:
     url: https://roboshop-builds.s3.amazonaws.com/cart.zip
     src: /tmp
  - name: unzipping cart code
    ansible.builtin.unarchive: 
     src: /tmp/cart.zip
     dest: /app
     remote_src: true
  - name: installing dependancies
    ansible.builtin.dnf:
     name: npm
     state: present
  - name: copying catalogue service
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service
  - name: reloading deamon
    ansible.builtin.systemd_service:
     daemon_reload: true
  - name: starting cart
    ansible.builtin.service:
     name: cart
     state: started
     enabled: true