- name: catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disable current nodejs and enabling nodejs 18
    ansible.builin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs 18
    ansible.builtin.command: dnf install nodejs -y
     name: nodejs
     state: present
  - name: adding application user
    ansible.builtin.user: 
     name: roboshop
  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  - name: downloading application code to the created directory
    ansible.builtin.command: curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
  - name: Store file into 
    ansible.builtin.fetch:
    src: /tmp/catalogue.zip
    dest: /app
  - name: downloading dependancies
    ansible.builtin.command: npm install
     state: present
  - name: copying file
    ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service
  - name: installing dependancies
    ansible.builtin.package: dnf install mongodb-org-shell -y
    state:present
  - name: loading schema
    ansible.builtin.command: mongo --host MONGODB-SERVER-IPADDRESS </app/schema/catalogue.js
  - name: reloading daemon
    ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
  - name: starting catalogue
    ansible.builtin.service:
     name: catalogue
     state: started
   - name: enabling catalogue
    ansible.builtin.service:
     name: catalogue
     enabled: yes
     