- name: user
  hosts: user
  become: yes
  tasks:
  - name: disable and enabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  - name: installing nodejs
    ansible.builtin.dnf: 
     name: nodejs
     state: present
  - name: adding roboshop user
    ansible.builtin.user:
     name: roboshop
  - name: creating app directory
    ansible.builtin.file:
     path: /app
     state: directory
  - name: download application code
    ansible.builtin.get_url: 
     url: https://roboshop-builds.s3.amazonaws.com/user.zip
     dest: /tmp
  - name: unzipping the code
    ansible.builtin.unarchive:
     src: /tmp/user.zip
     dest: /app
     remote_src: yes
  - name: installing dependancies
    ansible.builtin.dnf: 
     name: npm 
     state: present
  - name: copy user.service
    ansible.builtin.copy: 
     src: user.service
     dest: /etc/systemd/system/user.service
  - name: load the service
    ansible.builtin.systemd_service:
     name: user
     daemon_reload: true
  - name: copy user.service
    ansible.builtin.copy: 
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongo.repo
  - name: installing mongo-org
    ansible.builtin.dnf: 
     name: mongodb-org-shell
     state: present
  - name:  checking user data is loaded or not
    ansible.builtin.command: mongo --host mongodb.sowjanyaaws.xyz --quiet --eval 'db=db.getSiblingDB("users") ; db.users.count()'
    register: user_count
  - name: loading user data
    ansible.builtin.command: mongo --host mongodb.sowjanyaaws.xyz </app/schema/user.js
    when: user_count != "1"
  - name: starting & enabling the service
    ansible.builtin.service:
     name: user
     state: started
     enabled: true